### ISSUE TITLE
Compile error with Ard 1.8.13 and version 2.0

### ISSUE THREAD

**Issue by snowrodeo** [AndreaLombardo/L298N#11]
Arduino: 1.8.13 (Mac OS X), Board: "P1AM-100"

/Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.cpp: In member function 'void L298NX2::run(uint8_t)':
/Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.cpp:260:24: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'L298N::Direction' [-fpermissive]
   _motorA.run(direction);
                        ^
In file included from /Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.h:5:0,
                 from /Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.cpp:7:
/Users/erikolson/Documents/Arduino/libraries/L298N/src/L298N.h:28:9: error:   initializing argument 1 of 'void L298N::run(L298N::Direction)' [-fpermissive]
    void run(L298N::Direction direction);
         ^
/Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.cpp:261:24: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'L298N::Direction' [-fpermissive]
   _motorB.run(direction);
                        ^
In file included from /Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.h:5:0,
                 from /Users/erikolson/Documents/Arduino/libraries/L298N/src/L298NX2.cpp:7:
/Users/erikolson/Documents/Arduino/libraries/L298N/src/L298N.h:28:9: error:   initializing argument 1 of 'void L298N::run(L298N::Direction)' [-fpermissive]
    void run(L298N::Direction direction);
         ^
exit status 1
Error compiling for board P1AM-100.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by beestarbush** [comment]
I also encounter the issue by using platformio and putted more information of it on here regarding versions etc. Maybe you could use it for further investigation.

Thanks in advance!

Executing task in folder BlinkyApp: platformio run

Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
Verbose mode can be enabled via -v, --verbose option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (3.0.0) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.100200.0 (10.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 38 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Wire> 1.0
|-- <L298N> 2.0.1
|-- <PCF8574 library> 2.2.1
|   |-- <Wire> 1.0
Building in release mode
Compiling .pio/build/nodemcuv2/src/main.cpp.o
Compiling .pio/build/nodemcuv2/src/test.cpp.o
Generating LD script .pio/build/nodemcuv2/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/nodemcuv2/libe01/Wire/Wire.cpp.o
Compiling .pio/build/nodemcuv2/lib35f/L298N/L298N.cpp.o
Compiling .pio/build/nodemcuv2/lib35f/L298N/L298NX2.cpp.o
Compiling .pio/build/nodemcuv2/lib092/PCF8574 library/PCF8574.cpp.o
.pio/libdeps/nodemcuv2/L298N/src/L298NX2.cpp: In member function 'void L298NX2::run(uint8_t)':
.pio/libdeps/nodemcuv2/L298N/src/L298NX2.cpp:260:15: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'L298N::Direction' [-fpermissive]
  260 |   _motorA.run(direction);
      |               ^~~~~~~~~
      |               |
      |               uint8_t {aka unsigned char}
In file included from .pio/libdeps/nodemcuv2/L298N/src/L298NX2.h:5,
                 from .pio/libdeps/nodemcuv2/L298N/src/L298NX2.cpp:7:
.pio/libdeps/nodemcuv2/L298N/src/L298N.h:28:30: note:   initializing argument 1 of 'void L298N::run(L298N::Direction)'
   28 |    void run(L298N::Direction direction);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~
.pio/libdeps/nodemcuv2/L298N/src/L298NX2.cpp:261:15: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'L298N::Direction' [-fpermissive]
  261 |   _motorB.run(direction);
      |               ^~~~~~~~~
      |               |
      |               uint8_t {aka unsigned char}
In file included from .pio/libdeps/nodemcuv2/L298N/src/L298NX2.h:5,
                 from .pio/libdeps/nodemcuv2/L298N/src/L298NX2.cpp:7:
.pio/libdeps/nodemcuv2/L298N/src/L298N.h:28:30: note:   initializing argument 1 of 'void L298N::run(L298N::Direction)'
   28 |    void run(L298N::Direction direction);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~
*** [.pio/build/nodemcuv2/lib35f/L298N/L298NX2.cpp.o] Error 1
===================================== [FAILED] Took 8.52 seconds =====================================
The terminal process "platformio 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
`

**Comment by beestarbush** [comment]
Just looked into the code but just as a question/review comment: in the L298N.h the L298N::run(L298N::Direction direction); method has the type of L298N::Direction. Why is the argument of method L298NX2::run(uint8_t direction); a uint8_t instead of the L298N::Direction type?

**Comment by AndreaLombardo** [comment]
Hope solved by @beestarbush
