### ISSUE TITLE
Mistake in README.md

### ISSUE THREAD

**Issue by YariKartoshe4ka** [AndreaLombardo/L298N#8]
Same thing for L298NX2 variant
    
    // With Enable pin to control speed
    
                         motor A            motor B
                  |------------------||------------------|
    L298N myMotors(EN_A, IN1_A, IN2_A, EN_B, IN1_B, IN2_B);
    
    // Without Enable pin and jumper in place
    
                      motor A      motor B
                  |------------||------------|
    L298N myMotors(IN1_A, IN2_A, IN1_B, IN2_B);

I think you should change L298N to L298NX2 in this strings:

    L298N myMotors(EN_A, IN1_A, IN2_A, EN_B, IN1_B, IN2_B);
    L298N myMotors(IN1_A, IN2_A, IN1_B, IN2_B);

**Comment by AndreaLombardo** [comment]
Thanks @YariKartoshe4ka, you are right.
